name: Compile SEA
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Compile SEA
        run: npm run compile
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: SEA file
          path: dist/dualexe-sea
          compression-level: 9